"""
Centralized configuration for the AI Data Analyzer system.
All settings are read from environment variables with sensible defaults.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# ── Paths ────────────────────────────────────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent
UPLOAD_DIR = BASE_DIR / "uploads"
OUTPUT_DIR = BASE_DIR / "outputs"
UPLOAD_DIR.mkdir(exist_ok=True)
OUTPUT_DIR.mkdir(exist_ok=True)

# ── Server ───────────────────────────────────────────────────────────────
API_HOST = os.getenv("API_HOST", "0.0.0.0")
API_PORT = int(os.getenv("API_PORT", "8000"))
STREAMLIT_PORT = int(os.getenv("STREAMLIT_PORT", "8501"))
APP_BASE_URL = os.getenv("APP_BASE_URL", f"http://localhost:{API_PORT}")
# Internal URL used for container-to-container calls inside Docker network
API_INTERNAL_URL = os.getenv("API_INTERNAL_URL", APP_BASE_URL)

# ── Limits ───────────────────────────────────────────────────────────────
MAX_FILE_SIZE_MB = int(os.getenv("MAX_FILE_SIZE_MB", "50"))
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024
CHUNK_SIZE = int(os.getenv("CHUNK_SIZE", "100000"))  # 100k rows per chunk
MAX_ROWS_FULL = int(os.getenv("MAX_ROWS_FULL", "1000000"))

# ── LLM (optional) ──────────────────────────────────────────────────────
LLM_PROVIDER = os.getenv("LLM_PROVIDER", "none").lower()
LLM_API_KEY = os.getenv("LLM_API_KEY", "")
LLM_MODEL = os.getenv("LLM_MODEL", "gpt-4o-mini")
LLM_ENDPOINT = os.getenv(
    "LLM_ENDPOINT", "https://api.openai.com/v1/chat/completions"
)

def is_llm_enabled() -> bool:
    """Check if LLM is configured and enabled."""
    return LLM_PROVIDER != "none" and bool(LLM_API_KEY)

# ── Branding ─────────────────────────────────────────────────────────────
BRAND_NAME = os.getenv("BRAND_NAME", "AI Data Analyzer")
BRAND_COLOR = os.getenv("BRAND_COLOR", "#6C63FF")
BRAND_LOGO_URL = os.getenv("BRAND_LOGO_URL", "")
DEFAULT_BRAND = {
    "company_name": BRAND_NAME,
    "primary_color": BRAND_COLOR,
    "logo_path": None,
    "footer_text": f"Confidential — Generated by {BRAND_NAME}",
    "analyst_name": ""
}

# ── Scheduled Email Reports ──────────────────────────────────────────────
SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY", "")
SENDGRID_FROM_EMAIL = os.getenv("SENDGRID_FROM_EMAIL", "")
SCHEDULER_ENABLED = os.getenv("SCHEDULER_ENABLED", "false").lower() == "true"

# ── Auth ─────────────────────────────────────────────────────────────────
JWT_SECRET = os.getenv("JWT_SECRET", "")
API_KEY_ENTERPRISE = os.getenv("API_KEY_ENTERPRISE", "")

# ── Usage tracking ───────────────────────────────────────────────────────
ENABLE_USAGE_TRACKING = os.getenv("ENABLE_USAGE_TRACKING", "false").lower() == "true"

# ── Billing / Razorpay (optional until monetization is enabled) ───────
RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID", "")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET", "")
RAZORPAY_WEBHOOK_SECRET = os.getenv("RAZORPAY_WEBHOOK_SECRET", "")
RAZORPAY_PRO_PLAN_ID = os.getenv("RAZORPAY_PRO_PLAN_ID", "")
RAZORPAY_PORTAL_URL = os.getenv("RAZORPAY_PORTAL_URL", "")
