from dataclasses import dataclass
from typing import Optional

@dataclass
class BrandConfig:
    company_name: str = "AI Data Analyzer"
    primary_color: str = "#6C63FF"  # hex
    logo_path: Optional[str] = None
    footer_text: str = "Confidential — Generated by AI Data Analyzer"
    analyst_name: str = ""
